[package]
name = "blair_switch"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2.0"
macaddr = "1.0.1"
rustyline = "17.0.0"
crossbeam-channel = "0.5.15"
arc-swap = "1.7.1"
dashmap = "6.1.0"
